<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Admin.aspx.cs" Inherits="Admin" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .style1
        {
            width: 61px;
        }
        .style2
        {
            width: 82px;
        }
        .style4
        {
            width: 71px;
        }
        .style5
        {
            width: 128px;
        }
        .style6
        {
            width: 69px;
        }
        .style7
        {
            width: 96px;
        }
        .style8
        {
            width: 99px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    <center>
        <asp:RadioButtonList ID="RadioButtonList1" runat="server" AutoPostBack="True" 
            onselectedindexchanged="RadioButtonList1_SelectedIndexChanged">
            <asp:ListItem>Menu Item</asp:ListItem>
            <asp:ListItem>SlideShow Extender</asp:ListItem>
        </asp:RadioButtonList>
        <br />
        <table>
        <tr>
        <td align="center">
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" 
                onrowdeleting="GridView1_RowDeleting" 
                >
            </asp:GridView>
        </td>
        <td>
            <asp:Panel ID="PanelMenu" runat="server">
            <table>
        <tr>
        <td class="style1">
        
            <asp:Label ID="Label1" runat="server" Text="MenuName"></asp:Label>
        
        </td>
        <td class="style2">
        
            <asp:TextBox ID="txtMenu" runat="server"></asp:TextBox>
        
        </td>
        </tr>
        <tr>
        <td class="style1">
        
            <asp:Label ID="Label2" runat="server" Text="Menu URL"></asp:Label>
        
        </td>
        <td class="style2">
        
            <asp:TextBox ID="txturl0" runat="server"></asp:TextBox>
        
        </td>
        </tr>
        <tr>
        <td class="style1">
        
            &nbsp;</td>
        <td class="style2">
        
            <asp:Button ID="Button1" runat="server" onclick="Button1_Click" Text="Add" />
        
        </td>
        </tr>
        </table>
            </asp:Panel>
            <asp:Panel ID="PanelMenuColor" runat="server">
            <table>
            <tr>
            <td class="style4">
                <asp:Label ID="Label3" runat="server" Text="Menu BackColor"></asp:Label>
                </td><td class="style5">
                    <asp:DropDownList ID="DrMenuColor" runat="server" AutoPostBack="True">
                        <asp:ListItem>black</asp:ListItem>
                        <asp:ListItem>yellow</asp:ListItem>
                        <asp:ListItem>white</asp:ListItem>
                    </asp:DropDownList>
                </td>
            </tr>
                <tr>
                    <td class="style4">
                        &nbsp;</td>
                    <td class="style5">
                        <asp:Button ID="Button2" runat="server" onclick="Button2_Click" Text="Change" />
                    </td>
                </tr>
            </table>
            
            </asp:Panel>
            <asp:Panel ID="PanelSlide" runat="server">
            <table>
            <tr>
            <td class="style7">
                <asp:Label ID="Label4" runat="server" Text="Slide Image"></asp:Label>
                </td>
            <td class="style8">
                <asp:FileUpload ID="FileUpload1" runat="server" />
                </td>
            </tr>
                <tr>
                    <td class="style7">
                        &nbsp;</td>
                    <td class="style8">
                        <asp:Button ID="Button3" runat="server" onclick="SlideAdd_Click" Text="Add" />
                    </td>
                </tr>
            </table>
            </asp:Panel>
        </td>
        </tr></table>
        </center>
    </div>
    </form>
</body>
</html>
